version: '3.8'

volumes:
  data:

services:
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 6379:6379
  # myapp:
  #   image: [YOUR-APP-IMAGE]