version: '3.8'

volumes:
  data:

services:

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 6379:6379
    
  app:
    build: .
    container_name: antibruteforce
    image: app
    ports:
      - 8080:8080
    depends_on:
      - redis

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app