app:
  name: 'antibruteforce'
  version: '1.0.0'
  apiVersion: '1'

http:
  host: 'localhost'
  port: 8080

logger:
  logLevel: 'debug'

redis:
  redisHost: 'localhost'
  redisPort: 6379

capacity:
  n: 10
  m: 100
  k: 1000